Update mac_x64.yml
add xcode info

diff --git a/.github/workflows/mac_x64.yml b/.github/workflows/mac_x64.yml
--- a/.github/workflows/mac_x64.yml
+++ b/.github/workflows/mac_x64.yml
@@ -28,7 +28,7 @@ jobs:
       # Runs a single command using the runners shell
       - name: Run a one-line script
         run: echo Hello, world!
-             uname -a
+             uname -a # runs in single line and uname here not executed 
 
       # Runs a set of commands using the runners shell
       - name: Run a multi-line script
@@ -39,3 +39,6 @@ jobs:
           uname -a
           echo "df -h ./:"
           df -h ./
+          echo "xcode info:"
+          xcode-select -p || echo "xcode-select -p failed"
+          xcodebuild -version || echo "xcodebuild -version failed"
